.PHONY: cancellation-1-7

sqrt-pow-1-12: sqrt-pow-1-12.cpp
	g++ -lstdc++ -std=c++17 sqrt-pow-1-12.cpp -o sqrt-pow-1-12
	./sqrt-pow-1-12

cancellation-1-7: cancellation-1-7.cpp
	g++ -lstdc++ -std=c++17 cancellation-1-7.cpp -o cancellation-1-7
	./cancellation-1-7
