millerrabin: millerrabin.cpp
	g++ -std=c++17 -O3 millerrabin.cpp -o millerrabin.out
	time ./millerrabin.out

segsieve: segsieve.cpp
	g++ -std=c++17 -O3 segsieve.cpp -o segsieve.out
	time ./segsieve.out

primes2: primes2.cpp
	# g++ -std=c++17 -fsanitize=address -fsanitize=undefined primes2.cpp -o primes2.out
	g++ -std=c++17 -O3 primes2.cpp -o primes2.out
	time ./primes2.out
brckts: brckts.cpp
	g++ -std=c++17 -fsanitize=address -fsanitize=undefined brckts.cpp -o brckts.out
