450b: 450b.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall 450b.cpp -o450b

462b: 462b.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall 462b.cpp -o462b

289b: 289b.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall 289b.cpp -o289b

451b: 451b.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall 451b.cpp -o451b

315a: 315a.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall 315a.cpp -o315a


260a: 260a.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall 260a.cpp -o260a

69a: 69a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 69a.cpp -o69a

263a: 263a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 263a.cpp -o263a

266b: 266b.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 266b.cpp -o266b

32b: 32b.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 32b.cpp -o32b

271a: 271a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 271a.cpp -o271a

275a: 275a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 275a.cpp -o275a

59a: 59a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 59a.cpp -o59a


## template
XXXX: XXXX.cpp
	g++ -std=c++14 -O2 -fsanitize=address -fsanitize=undefined -Wall XXXX.cpp -oXXXX
