69a: 69a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 69a.cpp -o69a

263a: 263a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 263a.cpp -o263a

266b: 266b.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 266b.cpp -o266b

32b: 32b.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 32b.cpp -o32b

271a: 271a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 271a.cpp -o271a

275a: 275a.cpp
	g++ -O2 -fsanitize=address -fsanitize=undefined -Wall 275a.cpp -o275a
