duval.out: duval.cpp
	g++ -std=c++17 -fsanitize=address -fsanitize=undefined -O2 -g duval.cpp -o duval.out

hld.out: hld.cpp
	g++ -std=c++17 -fsanitize=address -fsanitize=undefined -O2 -g hld.cpp -o hld.out

dlx.out: dlx.cpp
	g++ -fsanitize=address -fsanitize=undefined -O2 -g dlx.cpp -o dlx.out

